In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {'ID':[1,2,3,4,5],
        'Name':['Amit','Priya',np.nan,'Rahul',np.nan],
        'Marks':[80,np.nan,75,85,np.nan],
        'city':['Ahm','BVN',np.nan,'Surat','Rajkot']}
df = pd.DataFrame(data)
df

   ID   Name  Marks    city
0   1   Amit   80.0     Ahm
1   2  Priya    NaN     BVN
2   3    NaN   75.0     NaN
3   4  Rahul   85.0   Surat
4   5    NaN    NaN  Rajkot

In [3]:
df.isnull()

      ID   Name  Marks   city
0  False  False  False  False
1  False  False   True  False
2  False   True  False   True
3  False  False  False  False
4  False   True   True  False

In [5]:
df.isnull().sum()

ID       0
Name     2
Marks    2
city     1
dtype: int64

In [10]:
df.fillna(130)

   ID   Name  Marks    city
0   1   Amit   80.0     Ahm
1   2  Priya  130.0     BVN
2   3    130   75.0     130
3   4  Rahul   85.0   Surat
4   5    130  130.0  Rajkot

In [16]:
df.fillna(df.mean())

   ID   Name  Marks    city
0   1   Amit   80.0     Ahm
1   2  Priya   80.0     BVN
2   3    NaN   75.0     NaN
3   4  Rahul   85.0   Surat
4   5    NaN   80.0  Rajkot

In [17]:
df.fillna(df.median())

   ID   Name  Marks    city
0   1   Amit   80.0     Ahm
1   2  Priya   80.0     BVN
2   3    NaN   75.0     NaN
3   4  Rahul   85.0   Surat
4   5    NaN   80.0  Rajkot

In [18]:
df.fillna(df.min())

   ID   Name  Marks    city
0   1   Amit   80.0     Ahm
1   2  Priya   75.0     BVN
2   3    NaN   75.0     NaN
3   4  Rahul   85.0   Surat
4   5    NaN   75.0  Rajkot

In [20]:
df.fillna(df.mode())

   ID   Name  Marks    city
0   1   Amit   80.0     Ahm
1   2  Priya   80.0     BVN
2   3  Rahul   75.0  Rajkot
3   4  Rahul   85.0   Surat
4   5    NaN    NaN  Rajkot