In [10]:
import pandas as pd
import numpy as np
df=pd.read_csv('car data.csv')
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [ ]:
df.drop('Car_Name',axis=1,inplace=True)
# column delete

In [4]:
df.head()

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [5]:
pd.get_dummies(df)

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
0,2014,3.35,5.59,27000,0,False,False,True,True,False,False,True
1,2013,4.75,9.54,43000,0,False,True,False,True,False,False,True
2,2017,7.25,9.85,6900,0,False,False,True,True,False,False,True
3,2011,2.85,4.15,5200,0,False,False,True,True,False,False,True
4,2014,4.60,6.87,42450,0,False,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,0,False,True,False,True,False,False,True
297,2015,4.00,5.90,60000,0,False,False,True,True,False,False,True
298,2009,3.35,11.00,87934,0,False,False,True,True,False,False,True
299,2017,11.50,12.50,9000,0,False,True,False,True,False,False,True
300,2016,5.30,5.90,5464,0,False,False,True,True,False,False,True

## Adding New Features

In [7]:
import pandas as pd
room_length=[18,20,10,12,18,11]
room_breadth=[20,20,10,11,19,10]
room_type=['Big','Big','Normal','Normal','Big','Normal']
data=pd.DataFrame({'Length':room_length,'Breadth':room_breadth,'Type':room_type})
data

   Length  Breadth    Type
0      18       20     Big
1      20       20     Big
2      10       10  Normal
3      12       11  Normal
4      18       19     Big
5      11       10  Normal

In [8]:
data['Area']=data["Length"]*data['Breadth']
data

   Length  Breadth    Type  Area
0      18       20     Big   360
1      20       20     Big   400
2      10       10  Normal   100
3      12       11  Normal   132
4      18       19     Big   342
5      11       10  Normal   110

In [9]:
data[data['Area']>300]

   Length  Breadth Type  Area
0      18       20  Big   360
1      20       20  Big   400
4      18       19  Big   342

## np.where()

In [11]:
# defining features
apartment_area=[4720,2430,4368,3969,6142,7912]
apartment_price=[2360000,1215000,2184000,1984500,3071000,3956000]
data4=pd.DataFrame({'Area':apartment_area,'Price':apartment_price})
data4

   Area    Price
0  4720  2360000
1  2430  1215000
2  4368  2184000
3  3969  1984500
4  6142  3071000
5  7912  3956000

In [12]:
data4['Price']=np.where(data4['Price']>3000000,'High',
                        np.where(data4['Price']<2000000,'Low','Medium'))
data4

   Area   Price
0  4720  Medium
1  2430     Low
2  4368  Medium
3  3969     Low
4  6142    High
5  7912    High

## Train Validation Split

In [ ]:
# function = train_test_split()
# x=dataframe,y=series
# x_train,x_test,y_train,y_test

## Arithmetic Opreation

In [ ]:
# arithmatic opreation value nan return generally nan
# ex. nan+1=nan
# logical opration involving nan return true or false depending on operations

In [13]:
df1=pd.DataFrame({'A':[1,2,None],'B':[4,None,6]})
df2=pd.DataFrame({'A':[1,None,3],'B':[None,5,6]})
result=df1+df2
print(result)

     A     B
0  2.0   NaN
1  NaN   NaN
2  NaN  12.0

## Cross Validation

In [ ]:
# not exam only for mcq
# k-fold cross-validation method
# fold  trainingfolds  test fold
# 1  2,3,4,5   1
# 2  1,3,4,5   2
# 3  1,2,4,5   3